### PR TITLE
Update html tag to also have a black background

### PR DESCRIPTION
**Pull request by xt0rted**
This fixes the issue where the `body` tag doesn't fill the screen and you're left with a white bar across the bottom. This can be seen at https://www.sitepoint.com/community/t/welcome-to-the-sitepoint-forums/118153/4 by scrolling to the bottom of the page.

I checked https://community.bitwarden.com and their `body` tag has `min-height: 100%;` so this looks to b a per theme issue. I figured it was better to set the color than to adjust the height.

### CODE REVIEW

**Comment by Podesta** [comment]
@xt0rted how would you feel about getting rid of the empty bottom altogether (like the other discourse forums) instead of just applying the background color to it?

**Comment by xt0rted** [comment]
Looks like my use of uBlock prevented me from seeing exactly why this white bar was there. They have a 150px margin on the body tag because they have a sticky footer with a banner ad. Removing the margin would cover the site content with that banner so I don't think we can remove it.

**Comment by Podesta** [comment]
Yeah, the sticky footer should be added to the transparent rule, as there is still a thin white line in the bottom. But I don't think there is any problem in removing the bottom margin. I don't think there is any content there, it is purely cosmetic. There is no proper footer to speak of (other than the sticky one that is also empty and needs to be made transparent), it just adds and empty space to the bottom of the page. 

But yeah, while removing it would make it consistent with other forums, there is indeed no real reason to remove it. Both are fine.

**Comment by Mottie** [comment]
Fixed. I added a background of `#222` instead of transparent since it may have content.

**Pull request merged**
