### PR TITLE
Add ubuntu-mate.community and reorder a few domains

### PR DESCRIPTION
**Pull request by Podesta**
Add [ubuntu-mate.community](https://ubuntu-mate.community) and reorder 2 others for consistency.
I personally don't mind the green header and footer (the colors of the project), but not sure if it aligns to your vision.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @Podesta!

Awesome! Thanks for your contribution!

What do you think about making the header and footer have a darker background color?

**Comment by Podesta** [comment]
Yes, absolutely! Same #111 or a ligher/darker shade?

**Comment by Mottie** [comment]
Up to you.

**Comment by Podesta** [comment]
Ok, I'll make it #111 to be uniform with the rest. But I'm absolutely fine with anything, feel free to change anything in the future.

**Pull request merged**
